x=[3 2 1 0 1 2 3]; 
a=length(x); 
n=-3:1:3;
subplot(4,1,1);
stem(n,x);
xlabel('number of samples');
ylabel('amplitude');
title('input signal');
m = (n-1);
subplot(4,1,2);
stem(m,x);
xlabel('number of samples');
ylabel('amplitude');
title('X(n + 1)');
x=[3 2 1 0 1 2 3];
n=-3:1:3;
m = n/2;
subplot(4,1,3);
stem(m,x);
xlabel('number of samples'); 
ylabel('amplitude'); 
title('X(2n)'); 
n=-3:1:3; 
x=[3 2 1 0 1 2 3]; 
m = (n+1)/3 ; 
subplot(4,1,4); 
stem(m,x); 
xlabel('number of samples'); 
ylabel('amplitude'); 
title('X(3n - 1)'); 
display(x); 
display(n); 
display(m);